# PERSONALIZATION SETTINGS
# These strings support HTML
author: "@estrattonbailey"
title: "ESTRATTONBAILEY"

# SOCIAL SETTINGS
# Fill these in with your URLs and simply un-comment them to enable
#
# social_map: "google maps URL"
# social_website: "your website URL"
social_twitter: "http://twitter.com/estrattonbailey"
social_facebook: "http://facebook.com/astronautpopsicle"
social_instagram: "http://instagram.com/estrattonbailey"
social_github: "http://github.com/estrattonbailey"
social_dribbble: "http://dribbble.com/estrattonbailey"
social_soundcloud: "http://soundcloud.com/estrattonbailey"
# social_youtube: "http://youtube.com/estrattonbailey"
# social_vimeo: "http://vimeo.com/estrattonbailey"
# social_flickr: "http://flickr.com/estrattonbailey"
# social_foursquare: "http://foursquare.com/estrattonbailey"
# social_pinterest: "http://pinterest.com/estrattonbailey"
# social_tumblr: "http://tumblr.com/estrattonbailey"
# social_googleplus: "http://google.com/estrattonbailey"



# # # # # #
# JEKYLL SETTINGS
#

# Web Server Settings
url: "http://localhost:4000"
# url: "http://estrattonbailey.github.io/estrattonbailey"

# Hide these files from jekyll build process.
exclude: [README.md, scss/, raw/, style.css.map]

# Pagination settings.
# More info: http://jekyllrb.com/docs/pagination/
paginate: 2
paginate_path: writings/page-:num

# Permalink setting for posts.
permalink: writings/:title



# Markdown Processors
markdown: kramdown
highlighter: pygments

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style