# SITE SETTINGS
homepage_title: Eric Bailey
homepage_headline: "A Developer Who Stil Calls Himself a Designer"
homepage_description: "Eric Bailey is a lover of simplicity and a maker of quality things. He enjoys being a teammate, learning, and seasonal beer offerings. Always from Iowa, currently from NYC."
# META
site_title: "Eric Bailey | Designer & Developer"
site_author: estrattonbailey
site_description: "Eric Bailey is a lover of simplicity and a maker of quality things. He enjoys being a teammate, learning, and seasonal beer offerings. Always from Iowa, currently from NYC."
site_keywords: "designer, developer"
# CUSTOMIZE 
color_theme: nominal # only one theme right now, sry
# SOCIAL
social_twitter: http://twitter.com/estrattonbailey
social_instagram: http://instagram.com/estrattonbailey
social_github: http://github.com/estrattonbailey
social_dribbble: http://dribbble.com/estrattonbailey


# JEKYLL - Misc
#
source: _src/
# Web Server Settings
# url: "http://localhost:4000"
url: "http://estrattonbailey.com"

# Hide these files from jekyll build process.
exclude: [README.md]
# Blog pagination settings.
paginate: 8
paginate_path: words/page-:num
# Permalink setting for posts.
permalink: words/:title
permalink_base: words/
# Build settings
markdown: redcarpet
# Sass Settings
sass:
  sass_dir: _scss
  style: :compact